//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DbStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManagerSystem.Database.DbStrings", typeof(DbStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server={0};Port={1};User Id={2};Password={3};Database={4};.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT (*) FROM &quot;accessControl&quot;.
        /// </summary>
        internal static string CountAccessControl {
            get {
                return ResourceManager.GetString("CountAccessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT (*) FROM &quot;colaborators&quot;.
        /// </summary>
        internal static string CountColaborators {
            get {
                return ResourceManager.GetString("CountColaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM &quot;accessControle&quot; WHERE &quot;pkCode&quot; = &apos;{0}&apos;.
        /// </summary>
        internal static string DeleteAccessControlByCode {
            get {
                return ResourceManager.GetString("DeleteAccessControlByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM &quot;accessControle&quot; WHERE &quot;username&quot; = &apos;{0}&apos;.
        /// </summary>
        internal static string DeleteAccessControlByUserName {
            get {
                return ResourceManager.GetString("DeleteAccessControlByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE * FROM &quot;accessControl&quot;.
        /// </summary>
        internal static string DeleteAllAccessControl {
            get {
                return ResourceManager.GetString("DeleteAllAccessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE * FROM &quot;colaborators&quot;.
        /// </summary>
        internal static string DeleteAllColaborators {
            get {
                return ResourceManager.GetString("DeleteAllColaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM &quot;colaborators&quot; WHERE {0}.
        /// </summary>
        internal static string DeleteColaborator {
            get {
                return ResourceManager.GetString("DeleteColaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;accessControl&quot; (&quot;userName&quot;, &quot;password&quot;, &quot;modules&quot;) VALUES (&apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;).
        /// </summary>
        internal static string InsertAccessControl {
            get {
                return ResourceManager.GetString("InsertAccessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;.
        /// </summary>
        internal static string InsertColumn {
            get {
                return ResourceManager.GetString("InsertColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;{0}&quot; ({1}) VALUES ({2}).
        /// </summary>
        internal static string InsertFormat {
            get {
                return ResourceManager.GetString("InsertFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;.
        /// </summary>
        internal static string InsertValue {
            get {
                return ResourceManager.GetString("InsertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM &quot;accessControl&quot; WHERE &quot;userName&quot; = &apos;{0}&apos;.
        /// </summary>
        internal static string SelectAccessCodeByUserName {
            get {
                return ResourceManager.GetString("SelectAccessCodeByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM &quot;accessControl&quot; WHERE &quot;pkCode&quot; = &apos;{0}&apos;.
        /// </summary>
        internal static string SelectAccessControlByCode {
            get {
                return ResourceManager.GetString("SelectAccessControlByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM &quot;accessControl&quot;.
        /// </summary>
        internal static string SelectAllAccessControl {
            get {
                return ResourceManager.GetString("SelectAllAccessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM &quot;colaborators&quot;.
        /// </summary>
        internal static string SelectAllColaborators {
            get {
                return ResourceManager.GetString("SelectAllColaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM &quot;colaborators&quot; WHERE {0}.
        /// </summary>
        internal static string SelectColaborator {
            get {
                return ResourceManager.GetString("SelectColaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE &quot;accessControl&quot; SET &quot;userName&quot; = &apos;{0}&apos;, &quot;password&quot; = &apos;{1}&apos; AND &quot;modules&quot; = &apos;{2}&apos; WHERE &quot;pkCode&quot; = &apos;{3}&apos;.
        /// </summary>
        internal static string UpdateAccessControl {
            get {
                return ResourceManager.GetString("UpdateAccessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE &quot;colaborators&quot; SET {0} WHERE &quot;rg&quot; = &apos;{1}&apos; AND &quot;cpf&quot; = &apos;{2}&apos; AND &quot;ctps&quot; = &apos;{3}&apos;.
        /// </summary>
        internal static string UpdateColaborator {
            get {
                return ResourceManager.GetString("UpdateColaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; = &apos;{1}&apos; AND &quot;{2}&quot; = &apos;{3}&apos; AND &quot;{4}&quot; = &apos;{5}&apos; AND &quot;{6}&quot; = &apos;{7}&apos;.
        /// </summary>
        internal static string WhereWithFourVariables {
            get {
                return ResourceManager.GetString("WhereWithFourVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; = &apos;{1}&apos;.
        /// </summary>
        internal static string WhereWithOneVariable {
            get {
                return ResourceManager.GetString("WhereWithOneVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; = &apos;{1}&apos; AND &quot;{2}&quot; = &apos;{3}&apos; AND &quot;{4}&quot; = &apos;{5}&apos;.
        /// </summary>
        internal static string WhereWithThreeVariables {
            get {
                return ResourceManager.GetString("WhereWithThreeVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; = &apos;{1}&apos; AND &quot;{2}&quot; = &apos;{3}&apos;.
        /// </summary>
        internal static string WhereWithTwoVariables {
            get {
                return ResourceManager.GetString("WhereWithTwoVariables", resourceCulture);
            }
        }
    }
}
