//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManagerSystem.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu algum erro com a inserção das informações do controle de acesso no banco de dados. Tente novamente. Se o problema persistir, contate o fornecedor..
        /// </summary>
        public static string AccessControlNotInserted {
            get {
                return ResourceManager.GetString("AccessControlNotInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As informações referentes ao endereço parecem incompletas. Deseja prosseguir assim mesmo?.
        /// </summary>
        public static string AddressBlankFileds {
            get {
                return ResourceManager.GetString("AddressBlankFileds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário digitar o Usuário.
        /// </summary>
        public static string BlankUserEntry {
            get {
                return ResourceManager.GetString("BlankUserEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O regitro de colaborador foi inserido com sucesso..
        /// </summary>
        public static string ColaboratorCorrectlyAdded {
            get {
                return ResourceManager.GetString("ColaboratorCorrectlyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu algum erro com a inserção do registro do colaborador no banco de dados. Tente novamente. Se o problema persistir, contate o fornecedor..
        /// </summary>
        public static string ColaboratorNotInserted {
            get {
                return ResourceManager.GetString("ColaboratorNotInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Colaborador.
        /// </summary>
        public static string ColaboratorRegistry {
            get {
                return ResourceManager.GetString("ColaboratorRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As informações de usuário e senha parecem incompletas. Deseja prosseguir assim mesmo?.
        /// </summary>
        public static string ControlAccessBlankFields {
            get {
                return ResourceManager.GetString("ControlAccessBlankFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor digitado para CPF é inválido..
        /// </summary>
        public static string CpfInvalidFormat {
            get {
                return ResourceManager.GetString("CpfInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um colaboratdor cadastrado com esta CNH..
        /// </summary>
        public static string HasAlreadyExistsColaboratorWithCnh {
            get {
                return ResourceManager.GetString("HasAlreadyExistsColaboratorWithCnh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um colaborador cadastrado com este CPF..
        /// </summary>
        public static string HasAlreadyExistsColaboratorWithCpf {
            get {
                return ResourceManager.GetString("HasAlreadyExistsColaboratorWithCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já esiste um colaborador cadastrado com este CTPS..
        /// </summary>
        public static string HasAlreadyExistsColaboratorWithCtps {
            get {
                return ResourceManager.GetString("HasAlreadyExistsColaboratorWithCtps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um colaborador cadastrado com este RG..
        /// </summary>
        public static string HasAlreadyExistsColaboratorWithRg {
            get {
                return ResourceManager.GetString("HasAlreadyExistsColaboratorWithRg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação Incorreta.
        /// </summary>
        public static string IncorrectInformation {
            get {
                return ResourceManager.GetString("IncorrectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha incorreta.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algumas informações possuem dados com formato inválido. Verifique os campos destacados em vermelho..
        /// </summary>
        public static string InvalidFormatInformation {
            get {
                return ResourceManager.GetString("InvalidFormatInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguns campos não podem ficar em branco. Verifique os campos destacados em vermelho..
        /// </summary>
        public static string NotAllowedBlankFileds {
            get {
                return ResourceManager.GetString("NotAllowedBlankFileds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi escolhido nenhum módulo de acesso para o colaborador. Deseja prosseguir assim mesmo?.
        /// </summary>
        public static string NotChosenAllowedModules {
            get {
                return ResourceManager.GetString("NotChosenAllowedModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A identificação de usuário já existe. Escolha uma identificação diferente..
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
